### ISSUE TITLE
seahawks data is outdated

### ISSUE THREAD

**Issue by cyclop22** [Tenzer/plugin.video.nfl-teams#7]
Hi I hope this addon is still maintained because I was using it a lot!

unfortunately there are no new videos on the seahawks channel since the playoffs.

**Comment by Tenzer** [comment]
Hi! Sorry about the late response, I only got around to test it today. I am seeing up to date videos with the NFL Teams plugin for Seahawks. Which version of the plugin do you have? The latest version is 1.3.2 and is available through the official repository.

**Comment by Tenzer** [comment]
I have updated the plugin now to version 1.3.3. It adds sorting by dates for teams such as Seahawks which should make it easier to see when new videos are added. The update has been submitted to the repository now ([PR](https://github.com/xbmc/repo-plugins/pull/1415)) and should hopefully soon be available for automatic updates in Kodi.

If you can't wait to try it out, you can also download a zip file with the latest release here: https://github.com/Tenzer/plugin.video.nfl-teams/releases/tag/v1.3.3.

**Comment by cyclop22** [comment]
Hi
I checked all the teams (all videos folder) and they all do have recent videos, except for the seahawks.
I thought maybe this was a cache issue so also tried to uninstall/install but nothing changed...

I run plugin version 1.3.3 on kodi 17.3 (openelec 8.0.4)

**Comment by Tenzer** [comment]
Hmm, I'm using a plugin (`script.common.plugin.cache`) for caching responses for websites to make the plugin quicker to navigate around in, but it's only set to cache items for 1 hour.

With version 1.3.3 of this plugin, if you navigate to "All videos" for Seahawks and sort by date, what is the most recent date you are shown?

**Comment by cyclop22** [comment]
Jan 13 2017

**Comment by Tenzer** [comment]
It could seem like my use of the cache plugin is wrong, and it just caches items forever when they are added. I'm sorry about this and I'll dig deeper into it soon!

**Comment by cyclop22** [comment]
man that was pretty cool. I pasted "script.common.plugin.cache" into my firefox url bar in order to search for it, maybe I can find a way to reset it, and it crashed firefox to kingdom come....

**Comment by Tenzer** [comment]
Awesome!

I've made a fix now, you can update manually via https://github.com/Tenzer/plugin.video.nfl-teams/releases/download/v1.3.4/plugin.video.nfl-teams-1.3.4.zip or wait until it shows up in the Kodi repository in a day or two (I'll submit it in a moment).

**Comment by cyclop22** [comment]
That worked - Thanks a lot! now all I need is an o-line.

**Comment by Tenzer** [comment]
Glad to hear it works now. I think we all could do with a new O-line (I'm a Cardinals fan).
